version: '3.10'
services:
  backend:
    build: .
    ports:
      - '8000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: tl_sql
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root

    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 33066:3306
  phpmyadmin:
    container_name: tl_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root

  server:
    container_name: tl_server
    build: .
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./app:/code/app
    depends_on:
      - db
    ports:
      - 8008:8000
    restart: on-failure
